filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      containers.ids:
        - "${data.docker.container.id}"
      exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elkb:9200}'
